### ISSUE TITLE
Tip: start mobile-first

### ISSUE THREAD

**Issue by Stefan-Espant** [KaanKalmi/look-and-feel-living-styleguide#8]
Wanneer je de layout van de styleguide wilt opmaken, kijk of je eerst een single-column layout kan opstellen en vervolgens kan uitbreiden naar een multi-column layout. Momenteel heeft het ontwerp een flinke marge aan twee kanten.

<img width="482" alt="Schermafbeelding 2023-11-15 om 11 41 15" src="https://github.com/KaanKalmi/look-and-feel-living-styleguide/assets/89298385/42f39e69-1fe9-4bb4-b92f-dae587702c43">

**Comment by smolgeorgie** [comment]
Schatjes, het is mobile first !! 

```css
body {
  margin: 0;
  font-family: "Halton", sans-serif;
  font-weight: normal;
  font-size: 1em;
  display: block;
  background-color: #272932;
  color: #ecf8f8;
}
``` 

zoals je kan zien, is het al wat kleiner in de body. hieronder zie je de media queries

```css
@media (min-width: 768px) and (max-width: 1024px) {
  body {
    font-size: 1.3em;
    /* Adjusted for tablets */
  }

  main {
    margin: 0 5em 5em 5em;
    /* Adjusted for tablets */
  }

  section {
    display: grid;
    grid-template-columns: 1fr;
    grid-template-areas:
      "titel"
      "voorbeeld"
      "info"
      "code";
  }

}

@media (min-width: 768px) {
  body {
    font-size: 1.5em;
    /* Adjusted for larger screens */
  }

  main {
    margin: 0 10em 10em 10em;
    /* Adjusted for larger screens */
  }

  section {
    display: grid;
    grid-template-columns: 1fr 1fr;
    grid-template-areas:
      "titel titel"
      "voorbeeld voorbeeld"
      "info code";
  }
```
